### PR TITLE
Refactor Resource to remove harness - Fixes #19

### LINKED ISSUE #19: Refactor Repository Folder Structure so Harness not Required
See https://github.com/PowerShell/DscResource.Tests/issues/225

### LINKED ISSUE #20: Add .VSCode Settings for PSScriptAnalyzer Rules
See https://github.com/PowerShell/DscResources/pull/424

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

- Added .VSCode settings for applying DSC PSSA rules - fixes [Issue #20](https://github.com/PlagueHO/FSRMDsc/issues/20).
- Refactored module folder structure to move resource
  to root folder of repository and remove test harness - Fixes [Issue #19](https://github.com/PlagueHO/FSRMDsc/issues/19).
- Converted Examples to support format for publishing to PowerShell
  Gallery.
- Opted into common tests:
  - Common Tests - Validate Example Files To Be Published
  - Common Tests - Validate Markdown Links
  - Common Tests - Relative Path Length
  - Common Tests - Relative Path Length
- Update to new format LICENSE.

#### This Pull Request (PR) fixes the following issues

- Fixes #19 
- Fixes #20 

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing? Sorry, this one is huge as it is a refactoring to get rid of the test harness and prepare all the examples to go to the gallery. No rush! :grin:

---
This change is [Reviewable](https://reviewable.io/reviews/plagueho/fsrmdsc/21)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
:lgtm:

I was many files, but rather quick to go through since it mostly renames. :slightly_smiling_face: 

> Reviewed 146 of 146 files at r1.
> *[Reviewable](https://reviewable.io/reviews/plagueho/fsrmdsc/21#-:-LNuVinH9CZpUFk8hy8-:b5x5v9r)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PlagueHO** [comment]
Awesome! Thank you so much @johlju - I appreciate that very much as I know it was pretty huge (and probably made Reviewable in your browser crawl).

**Comment by johlju** [comment]
It actually switched over to showing only single file, and the new button to approve and jump to the next file is awesome! Although, it's possible to press <kbd>n</kbd> to jump to the next file (to review) too. :)
But happy to get these through, only a few left of these until all the repos are converted? 😃

**Comment by PlagueHO** [comment]
Only a few more to go. Computermanagementdsc and networkingdsc and one more I think. Will be good when it is completed, because then I can focus on some features and other bug fixes.

**Pull request merged**
