### PR TITLE
Pull Request for Full Review

### PR DESCRIPTION
**Pull request by PlagueHO**
PR for performing a full module review.

See: https://github.com/PowerShell/DscResources/issues/70

---

This change is [Reviewable](https://reviewable.io/reviews/plagueho/fsrmdsc/2)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Wow. This module is _huge_ compared to the others we've been reviewing :elephant: :smile:  Gonna take a while to get through the code, but kudos for creating so many awesome resources! :+1: :star: 

---

Reviewed 2 of 100 files at r1.
Review status: 2 of 100 files reviewed at latest revision, 9 unresolved discussions.

---

_[appveyor.yml, line 4 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3ZnS1eq6QOgdqnuU:-KPE3ZnS1eq6QOgdqnuV:bw58r1r) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/appveyor.yml#L4)):_

> ``` YAML
> #      environment configuration  #
> #---------------------------------#
> version: 2.1.{build}.0
> ```

2.2.{build}.0

---

_[appveyor.yml, line 11 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3Fw8zSEb9OzIGqMh:-KPE3Fw8zSEb9OzIGqMi:bjd5hc6) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/appveyor.yml#L11)):_

> ``` YAML
>         cd DscResource.Tests
>         Import-Module .\TestHelper.psm1 -force
>         Pop-Location
> ```

This again

``` powershell
Import-Module .\DSCResource.Tests\TestHelper.psm1 -Force
```

---

_[appveyor.yml, line 43 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3cPuD0QGPnAtISVJ:-KPE3cPuD0QGPnAtISVK:banco9h) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/appveyor.yml#L43)):_

> ``` YAML
>       $stagingDirectory = (Resolve-Path ..).Path
>       $manifest = Join-Path $pwd "FSRMDsc.psd1"
>       (Get-Content $manifest -Raw).Replace("1.0.0.0", $env:APPVEYOR_BUILD_VERSION) | Out-File $manifest
> ```

2.2.0.0

---

_[FSRMDsc.psd1, line 7 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3hHxtuC8TLjrFmU2:-KPE3hHxtuC8TLjrFmU3:banco9h) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/FSRMDsc.psd1#L7)):_

> ``` PowerShell
> 
> # Version number of this module.
> ModuleVersion = '1.0.0.0'
> ```

2.2.0.0

---

_[FSRMDsc.psd1, line 19 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3iUN_r5WARLhPLwm:-KPE3iUN_r5WARLhPLwn:bt53p86) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/FSRMDsc.psd1#L19)):_

> ``` PowerShell
> 
> # Copyright statement for this module
> Copyright = '(c) 2015 Microsoft Corporation. All rights reserved.'
> ```

Update to 2016

---

_[README.md, line 5 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-ut1JMcQdsymytzD3:-KP-ut1JMcQdsymytzD4:bkm9c42) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L5)):_

> ``` Markdown
> # FSRMDsc
> The **FSRMDsc** module contains DSC resources for configuring Windows File Server Resource Manager.
> ```

Please add snippet about the MS open source code of conduct:

```
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.
```

---

_[README.md, line 658 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-w-BN6mn96lfSw0pa:-KP-w-BN6mn96lfSw0pb:bb9llfp) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L658)):_

> ``` Markdown
>             MailCC = 'fileserveradmins@contoso.com'
>             MailTo = '[Source Io Owner Email]'
>           DependsOn = "[FSRMQuotaTemplate]HardLimit5GB"
> ```

Please replace tab characters with 4 spaces

---

_[README.md, line 669 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-vvjdwx34lTQP16vR:-KP-vvjdwx34lTQP16vS:bb9llfp) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L669)):_

> ``` Markdown
>             Body = 'User [Source Io Owner] has exceed the [Quota Threshold]% quota threshold for quota on [Quota Path] on server [Server]. The quota limit is [Quota Limit MB] MB and the current usage is [Quota Used MB] MB ([Quota Used Percent]% of limit).'
>           EventType = 'Warning'
>           DependsOn = "[FSRMQuotaTemplate]HardLimit5GB"
> ```

Please replace tab characters with 4 spaces

---

_[README.md, line 683 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-vps64mMOuzWsMCsl:-KP-vps64mMOuzWsMCsm:bb9llfp) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L683)):_

> ``` Markdown
>             MailCC = 'fileserveradmins@contoso.com'
>             MailTo = '[Source Io Owner Email]'
>           DependsOn = "[FSRMQuotaTemplate]HardLimit5GB"
> ```

Please replace tab characters with 4 spaces

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-:-KPE6zNXHBE_ViK_QB0k:b-o2d07d)_

**Comment by PlagueHO** [comment]
I know - sorry about that :smile: - the FSRM feature in W2K12R2 is a pretty big (and I haven't actually implemented all of it yet). Thank you though - and I really appreciate the pain of reviewing a resource this big.

But what I'm thinking is that I should actually go through it first and fix up the problems that you have identified in the other reviews. Otherwise you'll spend heaps of time reporting the same issues.

So, shall I go through and fix up all the issues I know are there and then tag you when the module is ready for more review?

Incidentally, I wrote a blog post listing the issues you MSFT peeps had found in my code to hopefully help other people avoid them (and save you all some review pain). https://dscottraynsford.wordpress.com/2016/08/14/tips-for-hqrm-dsc-resources/

---

Review status: 1 of 100 files reviewed at latest revision, 9 unresolved discussions.

---

_[appveyor.yml, line 4 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3ZnS1eq6QOgdqnuU:-KPHau2CEDIWOStAkmxP:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/appveyor.yml#L4)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> 2.2.{build}.0
> </details>
> Done.

---

_[appveyor.yml, line 11 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3Fw8zSEb9OzIGqMh:-KPHauqfGw-Lr5cKpIBr:b-urihqt) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/appveyor.yml#L11)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> This again
> 
> ``` powershell
> Import-Module .\DSCResource.Tests\TestHelper.psm1 -Force
> ```
> 
> </details>
> Done. Sorry about that!

---

_[appveyor.yml, line 43 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3cPuD0QGPnAtISVJ:-KPHaxP0a26qxCreVwCW:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/appveyor.yml#L43)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> 2.2.0.0
> </details>
> Done.

---

_[FSRMDsc.psd1, line 7 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3hHxtuC8TLjrFmU2:-KPHb9Rj4AC001BFXOwL:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/FSRMDsc.psd1#L7)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> 2.2.0.0
> </details>
> Done.

---

_[FSRMDsc.psd1, line 19 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3iUN_r5WARLhPLwm:-KPHb9x8_bgC3A5WpWzu:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/FSRMDsc.psd1#L19)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Update to 2016
> </details>
> Done.

---

_[README.md, line 5 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-ut1JMcQdsymytzD3:-KPHcCgKjlm6zsuywoab:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L5)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Please add snippet about the MS open source code of conduct:
> 
> ```
> This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
> For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.
> ```
> 
> </details>
> Done.

---

_[README.md, line 658 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-w-BN6mn96lfSw0pa:-KPHbBobKB3TtAitdwCx:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L658)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Please replace tab characters with 4 spaces
> </details>
> Done.

---

_[README.md, line 669 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-vvjdwx34lTQP16vR:-KPHbDDYJDwpD0xgUrCp:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L669)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Please replace tab characters with 4 spaces
> </details>
> Done.

---

_[README.md, line 683 [r1]](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KP-vps64mMOuzWsMCsl:-KPHbDdNYYjHZUoANs-Y:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/README.md#L683)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Please replace tab characters with 4 spaces
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-:-KPHbFzpoKhazDBW5yZI:b-jqlpiz)_

**Comment by corydwood** [comment]
I just found that if you set the **EventNotificationLimit** parameter equal to **0** in the **FSRMSettings** resource, PowerShell interprets that as **$false** and never sets the value. This is most likely true for the **CommandNotificationLimit** and **EmailNotificationLimit** parameters as well.

**Comment by PlagueHO** [comment]
@corydwood - good catch! I'm planning on doing a bunch of work to this PR to get it up to HQRM over the next few weeks. It's a bit of a job due to the sheer size of this resource. But I'll include a fix to this as well.

**Comment by corydwood** [comment]
@PlagueHO - Changing **if (($EventNotificationLimit)...** to **if (($PSBoundParameters.ContainsKey('EventNotificationLimit'))...** appears to resolve this issue.

**Comment by PlagueHO** [comment]
@corydwood - nice!  Thank you. I started working on this module last night and will include your tests plus some regression tests for it. Much thanks for solving the problem!

**Comment by PlagueHO** [comment]
@kwirkykat - I've made all the changes to get this resource module up to HQRM - based on my past experiences with the reviews (e.g. my past mistakes). I'm sure there are still a few bits and pieces, but I think I've got the majority of the stuff.

I realize this is a bit of mega size resource and reviewing this will probably be the most boring thing ever and for that I am truly sorry 😭  

@corydwood - I've included your fixes! Thank you for identifying them and offering the solution!

**Comment by kwirkykat** [comment]
Reviewed 2 of 100 files at r1, 2 of 4 files at r2, 2 of 73 files at r4.
Review status: 7 of 117 files reviewed at latest revision, 11 unresolved discussions.

---

_[FSRMDsc.psd1, line 19 at r1](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3iUN_r5WARLhPLwm:-KWjYPXJ5827YH2lRbcm:b3kre) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/FSRMDsc.psd1#L19)):_
<details><summary>

<i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>



> Done.
> </details>
> ?

---

_[FSRMDsc.psd1, line 99 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjYZBMGI-hbeN40zxI:-KWjYZBMGI-hbeN40zxJ:bsqr7le) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/FSRMDsc.psd1#L99)):_

> ``` PowerShell
> 
>         # ReleaseNotes of this module
>         # ReleaseNotes = ''
> ```

ReleaseNotes = 'Initial release of FSRMDsc in the DSC Resource Kit'

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 215 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWj_JbpqtS8S9pFyZER:-KWj_JbpqtS8S9pFyZES:bubw7r) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L215)):_

> Test-ResourceProperty @PSBoundParameters

Why test the parameters here but not in Set-TargetResource?

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 291 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjZQg11LOjpOnE3kz0:-KWjZQg11LOjpOnE3kz1:biay0cw) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L291)):_

> ``` PowerShell
> #>
> Function Get-AutoQuota {
>     param (
> ```

Needs `[CmdletBinding()]` and `[OutputType([...])]`

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 326 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWj_ev_R1ZDA5J2fD3n:-KWj_eva6bD7UMoqPXUb:b-fi8ll7) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L326)):_

> Test-ResourceProperty

This function should use the verb `Assert` rather than `Test`. Functions with the `Test` verb return true or false (ex: `Test-ModuleImported` would return false if a module was not imported) while functions with the `Assert` verb throw errors if something is not as it should be (ex: `Assert-ModuleImported` would throw an error if the module was not imported).

I would suggest renaming this function to `Assert-ResourcePropertiesValid`

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 352 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjanWzb4alIj-ZkIwO:-KWjanX-8_s2EObQrdp8:b9i91iq) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L352)):_

> ``` PowerShell
>         $errorId = 'AutoQuotaPathDoesNotExistError'
>         $errorCategory = [System.Management.Automation.ErrorCategory]::InvalidArgument
>         $errorMessage = $($LocalizedData.AutoQuotaPathDoesNotExistError) -f $Path
> ```

Why not use New-InvalidArgumentException from CommonResourceHelper.psm1?

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 377 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjauIbp4hDzE73OJ0n:-KWjauIbp4hDzE73OJ0o:b9i91iq) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L377)):_

> ``` PowerShell
>         $errorId = 'AutoQuotaTemplateEmptyError'
>         $errorCategory = [System.Management.Automation.ErrorCategory]::InvalidArgument
>         $errorMessage = $($LocalizedData.AutoQuotaTemplateEmptyError) -f $Path
> ```

Why not use New-InvalidArgumentException from CommonResourceHelper.psm1?

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 386 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjav05VH_qhe04QfOd:-KWjav05VH_qhe04QfOe:b-pd5xhm) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L386)):_

> ``` PowerShell
>             -ArgumentList $exception, $errorId, $errorCategory, $null
> 
>         $PSCmdlet.ThrowTerminatingError($errorRecord)
> ```

Why not use New-InvalidOperationException from CommonResourceHelper.psm1?

---

_[DSCResources/MSFT_FSRMAutoQuota/en-us/MSFT_FSRMAutoQuota.strings.psd1, line 1 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjbLaWJkZIje4AOkCU:-KWjbLaWJkZIje4AOkCV:b-fwup0h) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/en-us/MSFT_FSRMAutoQuota.strings.psd1#L1)):_

> ``` PowerShell
> ConvertFrom-StringData -StringData @'
> ```

Can you please put spaces around all the equal signs?
(Find and replace '=' with ' = ')

---

_[DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1, line 30 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjbsJFvyoM4-V_FV6w:-KWjbsJFvyoM4-V_FV6x:b-ctcxqi) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1#L30)):_

> $Classification

lowercase: $classification

---

_[DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1, line 143 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjbddEmqLLLteJjk_H:-KWjbddEmqLLLteJjk_I:brsx15j) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1#L143)):_

> $splat 

Can you please  give this variable a more specific name?
(ex: $newScheduledTaskParameters)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2)_

**Comment by PlagueHO** [comment]
Thanks @KwirkyKat! I've done all the things you pointed out - except the conversion of the exception calls to use CommonResourceHelper.psm1. I'll get the error conversion done over the weekend and let you know when it is done.

Thanks again for reviewing this - it can't be fun.

---

Review status: 7 of 117 files reviewed at latest revision, 11 unresolved discussions.

---

_[FSRMDsc.psd1, line 19 at r1](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KPE3iUN_r5WARLhPLwm:-KWqD4JSIuiafXKRSEaX:b-rg7ovv) ([raw file](https://github.com/plagueho/fsrmdsc/blob/be869dc405e1073484227b6dbcbf0360b35482bb/FSRMDsc.psd1#L19)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> ?
> </details>
> Sorry - I did the License - but not the PSD1. Done now.

---

_[FSRMDsc.psd1, line 99 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjYZBMGI-hbeN40zxI:-KWqDH2GDtihjINaNuNp:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/FSRMDsc.psd1#L99)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> ReleaseNotes = 'Initial release of FSRMDsc in the DSC Resource Kit'
> </details>
> Done.

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 215 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWj_JbpqtS8S9pFyZER:-KWqDUURQk_6AFhNndJ5:b-bolc4n) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L215)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> > Test-ResourceProperty @PSBoundParameters
> 
> Why test the parameters here but not in Set-TargetResource?
> </details>
> Good question. When I first wrote this I made the assumption that the `Set-TargetResource` would never fire without `Test-TargetResource` firing- which is the case for DSC running the resource I think. But when the `Invoke-DSCResource` cmdlet came along it invalidated that assumption. So... I'll go through and add this to all the `Set-TargetResource`functions too. :grin:

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 291 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjZQg11LOjpOnE3kz0:-KWqFUYXKfxXiqr1hBHL:b-896fix) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L291)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Needs `[CmdletBinding()]` and `[OutputType([...])]`
> </details>
> Done.

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 326 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWj_ev_R1ZDA5J2fD3n:-KWqFvbcCUcdAGHMdNKJ:b8ndah1) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L326)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> > Test-ResourceProperty
> 
> This function should use the verb `Assert` rather than `Test`. Functions with the `Test` verb return true or false (ex: `Test-ModuleImported` would return false if a module was not imported) while functions with the `Assert` verb throw errors if something is not as it should be (ex: `Assert-ModuleImported` would throw an error if the module was not imported).
> 
> I would suggest renaming this function to `Assert-ResourcePropertiesValid`
> </details>
> A really excellent point. Done.

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 352 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjanWzb4alIj-ZkIwO:-KWqG0DHsWHk4bYrHbt5:b37r9m2) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L352)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Why not use New-InvalidArgumentException from CommonResourceHelper.psm1?
> </details>
> A good suggestion. I'll spend some time and do some conversion over to use the errors in CommonResourceHelper.psm1. I'll let you know where it is complete :)

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 377 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjauIbp4hDzE73OJ0n:-KWqGGJZjeVPk-B-NR12:b-q64pkt) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L377)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Why not use New-InvalidArgumentException from CommonResourceHelper.psm1?
> </details>
> See above.

---

_[DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1, line 386 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjav05VH_qhe04QfOd:-KWqGHGjxIJryYwcwKfI:b-q64pkt) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/MSFT_FSRMAutoQuota.psm1#L386)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Why not use New-InvalidOperationException from CommonResourceHelper.psm1?
> </details>
> See above.

---

_[DSCResources/MSFT_FSRMAutoQuota/en-us/MSFT_FSRMAutoQuota.strings.psd1, line 1 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjbLaWJkZIje4AOkCU:-KWqHcuUAF0wPBIdRGy4:b-twyxl9) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMAutoQuota/en-us/MSFT_FSRMAutoQuota.strings.psd1#L1)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> Can you please put spaces around all the equal signs?
> (Find and replace '=' with ' = ')
> </details>
> Done (in all strings files).

---

_[DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1, line 30 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjbsJFvyoM4-V_FV6w:-KWqHx9ljKm_GbhpVfAI:bm30onz) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1#L30)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> > $Classification
> 
> lowercase: $classification
> </details>
> I thought I'd got them all - but obviously not. Great catch. Fixed.

---

_[DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1, line 143 at r4](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-KWjbddEmqLLLteJjk_H:-KWqILh7hWIM8pcfS3aP:b-964vj9) ([raw file](https://github.com/plagueho/fsrmdsc/blob/d29a0e563b242866b1e9fbed39b29382b1270736/DSCResources/MSFT_FSRMClassification/MSFT_FSRMClassification.psm1#L143)):_
<details><summary>

<i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>



> > $splat 
> 
> Can you please  give this variable a more specific name?
> (ex: $newScheduledTaskParameters)
> </details>
> Done. I checked the other resources for the same problem as well. I've used $splat in the unit tests - but I think this should be OK?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-:-KWqIWRT3sRAPKdehcyv:bt1gutq)_

**Comment by PlagueHO** [comment]
@kwirkykat - Ok. All ready to review again. I have:
- Eliminated the PSSA rule violations
- Converted the Integration tests to use $TestDrive (because all integration tests started failing).
- Converted all custom exception code to use CommonResourceHelper.psm1 and CommonTestsHelper.psm1

---

Review status: 6 of 118 files reviewed at latest revision, 11 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/plagueho/fsrmdsc/2#-:-KWu8j6wnsvksnkNMyfv:bqx9nnm)_

**Pull request merged**
